name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the numver square
    steps:
      -name: Cehckout
       uses: actions/checkout@v2
      -name: Fetch num squared
       id: et_square
       uses: ./
       with:
        num: 11
      -name: print the square
       run: echo "${{steps.get_square.outputs.num_squared}}"
